'use strict';
const dialog=document.querySelector('#panel'),content=document.querySelector('#panel-content');
let lastFocus;
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const intro=(label,title,body='')=>`<span class="eyebrow">${label}</span><h2 id="panel-title">${title}</h2>${body?`<p class="lead">${body}</p>`:''}`;
const note='<p class="footnote">Project and channel results are reported from my portfolio and campaign records.</p>';
const asset=n=>`assets/${n}`;
function picture(src,alt,cls=''){return `<img class="${cls}" src="${asset(src)}" alt="${esc(alt)}" loading="lazy" decoding="async">`;}
function phone(src,alt){return `<div class="iphone">${picture(src,alt)}<span class="iphone-camera" aria-hidden="true"></span></div>`;}
function visual(src,alt,caption='',cls=''){return `<figure class="case-visual ${cls}">${picture(src,alt)}${caption?`<figcaption>${esc(caption)}</figcaption>`:''}</figure>`;}
function masked(type){
 const defs={
  direct:{box:'275 130 812 1224',w:1282,h:1354,file:'rev-sunny-direct.webp',shape:'<rect x="282" y="131" width="796" height="1750" rx="145"/><rect x="275" y="375" width="810" height="975"/>',alt:'Sunnyness Instagram Direct flow, in the original cropped iPhone'},
  travel:{box:'60 28 635 822',w:762,h:898,file:'rev-alaedin-social.webp',shape:'<rect x="61" y="29" width="357" height="727" rx="64"/><rect x="333" y="127" width="357" height="721" rx="56"/>',alt:'Alaedin Instagram and LinkedIn in overlapping iPhones'},
  mac:{box:'7 74 1013 598',w:1020,h:740,file:'rev-alaedin-web.webp',shape:'<rect x="103" y="74" width="825" height="576" rx="30"/><path d="M8 636H1020V650Q970 671 920 672H115Q40 671 7 653Z"/>',alt:'Alaedin travel article displayed on a MacBook'}
 };const v=defs[type];return `<figure class="case-visual masked-${type}"><svg viewBox="${v.box}" role="img" aria-label="${v.alt}"><defs><clipPath id="clip-${type}">${v.shape}</clipPath></defs><image href="${asset(v.file)}" width="${v.w}" height="${v.h}" clip-path="url(#clip-${type})"/></svg></figure>`;
}
function storyRow(files,label,cls=''){return `<div class="story-row ${cls}" tabindex="0" aria-label="${esc(label)}">${files.map((file,i)=>`<figure>${phone(file,`${label}, ${i+1}`)}<figcaption>${String(i+1).padStart(2,'0')}</figcaption></figure>`).join('')}</div>`;}
const section=(title,body,media)=>`<section class="case-section"><h3>${title}</h3><p class="case-copy">${body}</p>${media}</section>`;
function caseStudy(p){
 switch(p.id){
 case 'project-1': return `<div class="case-pair">${visual('work-snapp-web.webp','Snapp Barcode website and product on Mac and iPhone')}${visual('work-snapp-social.webp','Snapp Barcode Instagram and Baleh channels')}</div>`;
 case 'project-2': return visual('rev-sunny-games.webp','Sunny Shoot, Sunny Flip and Sunny Slash mini-games','', 'wide-art')+
 section('A shorter route from curiosity to play','I shaped the Instagram Direct flow around a clear sequence: discover the games, understand the next step and start playing. Short prompts and a consistent, cheerful tone connected the mini-games with the brand promise. The flow also acknowledged connection disruptions so the communication stayed useful when the experience was interrupted.',masked('direct'))+
 section('Campaign content people watched','Campaign posts brought the games into the Instagram feed and gave people a reason to explore the activation. Across the campaign posts, views approached 10 million, as reported in my campaign brief. I used the campaign identity and game moments consistently so the feed supported the same experience as Direct.',`<div class="single-phone">${phone('rev-sunny-reels.webp','Sunnyness campaign Instagram posts and view counts')}</div>`)+
 section('Copy that invites participation','I connected playful copy with clear instructions and reasons to join in. The story sequence introduced the activation, explained the games and rewards, and guided people toward participation while keeping Sunnyness’ upbeat voice.',storyRow([1,2,3,4,5,6].map(i=>`rev-sunny-story-${i}.webp`),'Sunnyness campaign stories','stories-six'));
 case 'project-3': return `<div class="creative-trio">${['cake','sandwich','sushi'].map(n=>visual(`rev-pakshoma-${n}.webp`,`Pakshoma Your Ideal Home ${n} campaign creative`)).join('')}</div>`+
 section('An invitation to imagine your ideal home','I contributed to copy and campaign communication that connected the refrigerator with everyday aspirations. The stories opened with a relatable question, introduced the campaign promise and directed the audience toward the next step. Consistent wording helped the creative feel like one conversation across the campaign.',storyRow([2,3,1].map(i=>`rev-pakshoma-story-${i}.webp`),'Pakshoma campaign stories'));
 case 'project-4': return visual('rev-rozet-feed.webp','Rozet Group coordinated Instagram content grid','','feed-art')+
 section('Content pillars with a clear role','I organized content around the group’s different audiences: company and sector updates, industry news, educational posts and brand culture. A shared visual system gave those pillars consistency while letting each format serve a different purpose. The examples below follow the order of the original content selection.',storyRow([9,8,1,4,3,2,6,5,7].map(i=>`rev-rozet-story-${i}.webp`),'Rozet content examples','stories-grid'))+
 section('Making the website a useful publishing channel','I worked on website content and the publication of news and articles, connecting social topics with more detailed information on the site. Clearer organization and consistent publishing supported discoverability and gave audiences a useful place to continue reading.',visual('rev-rozet-news.webp','Rozet website latest news and articles','','wide-art'));
 case 'project-5':return visual('work-citadium.webp','Citadium Instagram channels and website in original iPhone and Mac frames');
 case 'project-6':return visual('work-kanirush.webp','Kanirush Instagram and store in iPhone and Mac frames')+
 section('LinkedIn strategy & growth','Developed content strategies to enhance brand visibility, recruit top talent, and build strategic partnerships with industry leaders.', '')+
 section('Pinterest marketing & visual identity','Curated cohesive, high-quality visual content for clothing brands, leveraging trends and algorithms to drive organic reach.',visual('work-kanirush-channels.webp','Kanirush Pinterest and LinkedIn in iPhone frames'))+
 '<p class="case-copy key-impact"><strong>Key impact:</strong> Boosted brand discoverability, increased targeted website traffic, optimized conversion rates, and drove long-term audience engagement.</p>';
 case 'project-7':return masked('mac')+section('One calendar, different channel roles','I built content calendars across Instagram, LinkedIn and Aparat, connecting timely travel themes with SEO articles and video. Each channel had its own format and audience, while shared topics kept planning and publishing consistent. Website articles offered more depth, and social content helped people discover them.',masked('travel'));
 case 'project-8':return visual('work-firoozeh.webp','Firoozeh video and campaign creative, preserving the original composition');
 case 'project-9':return visual('work-iriano.webp','Iriano Instagram and online store in iPhone and Mac frames');
 }
}
function companyCard(c){return `<a class="project-card company-card" href="#${c.route||c.id}"><div class="company-photo">${picture(c.image,`${c.title} selected visual`)}</div><span class="card-date">${esc(c.date)}</span><h3>${esc(c.title)} <span aria-hidden="true">↗</span></h3><p>${esc(c.description)}</p></a>`;}
function projectCard(p){let src=p.id==='project-2'?'work-sunnyness-brand.webp':p.id==='project-3'?'work-pakshoma.webp':p.id==='project-4'?'work-rozet.webp':'work-citadium.webp';return `<a class="project-card subproject-card" href="#${p.id}"><div class="subproject-photo">${picture(src,p.title)}</div><h3>${esc(p.title)} <span aria-hidden="true">↗</span></h3><p>${esc(p.intro)}</p></a>`;}
function render(route){
 if(route==='work')return intro('EXPERIENCE & SELECTED WORK','My work.','The companies I have worked with, and the projects behind them.')+`<div class="project-list company-list">${companies.map(companyCard).join('')}</div>`;
 const company=companies.find(c=>c.id===route&&c.children);
 if(company)return `<a class="back-link" href="#work">← All companies</a>`+intro(esc(company.date+' / '+company.role),esc(company.title),esc(company.description))+`<div class="project-list subproject-list">${company.children.map(id=>projectCard(projects.find(p=>p.id===id))).join('')}</div>`;
 const p=projects.find(p=>p.id===route);
 if(p){const parent=companies.find(c=>c.children?.includes(p.id));return `<a class="back-link" href="#${parent?.id||'work'}">← ${parent?esc(parent.title):'All companies'}</a>`+intro(esc(p.role),esc(p.title),esc(p.intro))+`<div class="detail-intro"><section><span class="eyebrow">MY CONTRIBUTION</span><ul>${p.bullets.map(b=>`<li>${esc(b)}</li>`).join('')}</ul>${p.id==='project-1'?'<a class="back-link" href="#collaboration">Explore team collaboration ↗</a>':''}</section><aside class="result"><span class="eyebrow">KEY ACHIEVEMENTS</span><strong>${esc(p.metric)}</strong><p>${esc(p.result.replace('*',''))}</p></aside></div><div class="case-study">${caseStudy(p)}</div><p class="tags">${esc(p.tags)}</p>`+(p.result.includes('*')?note:'');}
 if(route==='achievements')return `<h2 id="panel-title" class="sr-only">Key achievements</h2><img class="achievement-reference" src="assets/rev-achievements.webp" alt="My key achievements: a gamification campaign with 21M+ impressions; 10.72% organic follower growth for Citadium Mall in seven months; 300+ leads in the first week after the outage; content systems for more than six brands; and end-to-end content pipelines."><div class="achievement-mobile"><p>I have a proven track record in driving growth and engagement across multiple industries through data-driven strategies, content optimization, and effective campaign management.</p><ol>${['Designed a high-engagement gamification campaign with <strong>21M+ impressions</strong>','<strong>+10.72%</strong> organic follower growth for Citadium Mall in 7 months','Turned post-outage demand into <strong>300+ leads</strong> in the first week','Developed multi-platform content systems for <strong>6+ brands</strong>','Built end-to-end content pipelines'].map((t,i)=>`<li><span>0${i+1}</span><p>${t}</p></li>`).join('')}</ol></div>`;
 if(route==='about')return intro('ABOUT ME','Curious by nature.<br>Connected in my work.','I’m Melika, a digital marketing generalist with 5+ years of experience across e-commerce, fashion, retail, travel and B2B SaaS.')+`<div class="about-story"><p>I’m an observer. I pay attention to how people talk, what makes them stop scrolling and where their experience becomes confusing. I enjoy finding the small insight that can make a message clearer or a piece of content more useful.</p><p>My interests sit where audience behavior, visual storytelling and digital experiences meet. I like exploring how brands build a recognizable voice, how communities respond to an idea and how creative work can improve through feedback.</p><p>I work across strategy, content, campaign planning and performance review. I connect the people involved, turn insights into practical briefs and stay close to production and delivery. Working across industries has taught me to adapt quickly without losing sight of the audience or the business objective.</p></div><div class="skill-grid">${[['Strategy & content','Audience research, positioning, content pillars and calendars.'],['Creative & campaigns','Campaign concepts, brand storytelling and creative direction.'],['Performance & discovery','Analytics, SEO copywriting, paid-media coordination and A/B test collaboration.'],['People & delivery','Agency collaboration, community management and project coordination.']].map(([h,b])=>`<section class="skill"><h3>${h}</h3><p>${b}</p></section>`).join('')}</div><section class="certifications"><h3 class="section-title">My certifications</h3><div class="badge-line">${picture('rev-certifications.webp','Certification providers from my resume: Meta, Google, Coursera, Yonsei University, Dubai Future Foundation and UC Davis')}</div><a class="back-link" href="https://www.linkedin.com/in/melikakamalifard" target="_blank" rel="noopener noreferrer">Explore my certifications on LinkedIn ↗</a></section><h3 class="section-title">Education</h3><p>Bachelor of Biomedical Engineering<br>Islamic Azad University, South Branch / 2017</p><a class="back-link" href="#experience">Explore my experience ↗</a>`;
 if(route==='collaboration')return intro('CROSS-FUNCTIONAL COLLABORATION','Better work.<br>Built together.','I connect audience insight, creative execution and the people needed to deliver a project.')+`<div class="about-story"><p>As a generalist, I work across team boundaries. I translate customer questions and performance feedback into content briefs, coordinate with design and production, and keep agencies and internal teams aligned around the same campaign objective.</p><p>My project management work includes organizing content calendars, clarifying deliverables, coordinating reviews and following work through publication. When priorities or conditions change, I help the team adapt the plan and keep communication consistent.</p></div><div class="skill-grid">${[['Data & customer insight','At Snapp Barcode, I worked with Data to build content pillars around product features and audience needs.'],['Customer Service & messaging','I used recurring customer questions and pain points to make messages more relevant and useful.'],['Design & Performance','I reviewed banner CTR feedback, coordinated creative revisions and supported A/B testing conversations between the teams.'],['Agencies & production','I coordinated content and agency activity, turning strategy into briefs, production plans and publishing schedules.']].map(([h,b])=>`<section class="skill"><h3>${h}</h3><p>${b}</p></section>`).join('')}</div><div class="flow"><div><strong>01 / Align</strong><p>Clarify the objective, audience, responsibilities and deliverables.</p></div><div><strong>02 / Coordinate</strong><p>Connect teams, organize reviews and keep production moving.</p></div><div><strong>03 / Improve</strong><p>Review feedback and results, then refine the next iteration.</p></div></div><h3 class="section-title">Recommendations</h3><div class="recommendations">${recommendations.map((r,i)=>`<figure class="recommendation"><svg viewBox="${r.x} 169 322 432" role="img" aria-labelledby="rec-title-${i}"><title id="rec-title-${i}">${esc(r.name+', '+r.role+'. '+r.quote)}</title><image href="assets/rev-recommendations.webp" width="1366" height="768"/></svg><figcaption class="sr-only">${esc(r.name)} — ${esc(r.role)}</figcaption></figure>`).join('')}</div><a class="back-link" href="#project-1">View Snapp Barcode ↗</a>`;
 if(route==='experience')return intro('CAREER','Experience.','Digital marketing across B2B SaaS, retail, fashion and travel.')+`<ol class="timeline">${companies.map(c=>`<li><span>${esc(c.date)}</span><div><h3><a href="#${c.route||c.id}">${esc(c.title)}</a></h3><p>${esc(c.role)}</p></div></li>`).join('')}</ol><a class="back-link" href="#work">Explore my work ↗</a>`;
 return null;
}

function sync(){const route=location.hash.slice(1),html=render(route);if(!html){if(dialog.open)dialog.close();return;}if(!dialog.open)lastFocus=document.activeElement;dialog.dataset.route=route;content.innerHTML=html;if(!dialog.open)dialog.showModal();dialog.scrollTop=0;document.querySelector('#close').focus();}
function closePanel(){history.replaceState(null,'',location.pathname+location.search);dialog.close();if(lastFocus?.isConnected)lastFocus.focus();}
document.querySelector('#close').addEventListener('click',closePanel);
document.querySelector('#back-home').addEventListener('click',e=>{e.preventDefault();closePanel();});
dialog.addEventListener('cancel',e=>{e.preventDefault();closePanel();});
dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closePanel();}});
window.addEventListener('hashchange',sync);
const mode=document.querySelector('#mode');
function setMode(minimal){document.body.classList.toggle('minimal',minimal);mode.setAttribute('aria-pressed',String(minimal));mode.setAttribute('aria-label',minimal?'Switch to colorful appearance':'Switch to minimal appearance');mode.querySelector('span').textContent=minimal?'Colorful':'Minimal';}
try{setMode(localStorage.getItem('portfolio-minimal')==='true');}catch{}
mode.addEventListener('click',()=>{const minimal=!document.body.classList.contains('minimal');setMode(minimal);try{localStorage.setItem('portfolio-minimal',String(minimal));}catch{}});
sync();
