'use strict';
const dialog=document.querySelector('#panel'),content=document.querySelector('#panel-content');
let lastFocus;
const esc=s=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const intro=(label,title,body='')=>`<span class="eyebrow">${label}</span><h2 id="panel-title">${title}</h2>${body?`<p class="lead">${body}</p>`:''}`;
const note='<p class="footnote">* Reported project/channel results from the original portfolio; not independently verified.</p>';
function render(route){
 if(route==='work')return intro('SELECTED PROJECTS','My work.','Campaign strategy, creative optimization and customer insight.')+`<div class="project-list">${projects.map(p=>`<a class="project-card" href="#${p.id}"><div class="project-photo ${p.visuals[0].zoom?'is-zoomed':''}">${`<img src="${p.visuals[0].src}" alt="${esc(p.visuals[0].alt)}" loading="lazy" decoding="async">`}</div><h3>${esc(p.title)} ↗</h3><p>${esc(p.intro)}</p></a>`).join('')}</div>`;
 const p=projects.find(p=>p.id===route);
 if(p)return `<a class="back-link" href="#work">← All projects</a>`+intro(esc(p.role),esc(p.title),esc(p.intro))+`<div class="detail-intro"><section><span class="eyebrow">MY CONTRIBUTION</span><ul>${p.bullets.map(b=>`<li>${esc(b)}</li>`).join('')}</ul>${p.id==='project-1'?'<a class="back-link" href="#collaboration">Explore team collaboration ↗</a>':''}</section><aside class="result"><span class="eyebrow">KEY ACHIEVEMENTS</span><strong>${esc(p.metric)}</strong><p>${esc(p.result)}</p></aside></div><div class="gallery gallery--${p.visuals.length}">${p.visuals.map(v=>`<figure class="work-visual"><div class="visual-stage ${v.zoom?'is-zoomed':''}"><img src="${v.src}" alt="${esc(v.alt)}" decoding="async"></div><figcaption>${esc(v.caption)}</figcaption></figure>`).join('')}</div><p class="tags">${esc(p.tags)}</p>`+(p.result.includes('*')?note:'');
 if(route==='about')return intro('ABOUT ME','A broader marketing perspective.','I turn customer insight into clear messages, coordinated campaigns and better creative.')+`<div class="skill-grid">${[['Strategy','Audience research & positioning'],['Creative','Campaign ideas & content systems'],['Performance','CTR review & A/B test collaboration'],['Collaboration','Data, service, design & performance']].map(([h,b])=>`<section class="skill"><h3>${h}</h3><p>${b}</p></section>`).join('')}</div><h3 class="section-title">Across industries.</h3><p class="lead">B2B SaaS / Retail / Fashion / Travel / Consumer brands</p><h3 class="section-title">Education</h3><p>B.Sc. Biomedical Engineering<br>Islamic Azad University, South Branch / 2017</p><a class="back-link" href="#experience">Explore my experience ↗</a>`;
 if(route==='achievements')return intro('SELECTED IMPACT','Key achievements.','Campaigns, growth and the systems behind them.')+`<ol class="numbered">${[['21M+ campaign impressions','Sunnyness gamification activation.*'],['+10.72% organic growth','Citadium Mall, over 7 months.*'],['300+ leads in week one','Snapp Barcode launch.'],['Content systems for 6+ brands','Consistent planning across channels and industries.*'],['End-to-end content pipelines','From audience insight to production and optimization.']].map(([h,b])=>`<li><div><h3>${h}</h3><p>${b}</p></div></li>`).join('')}</ol>`+note;
 if(route==='collaboration')return intro('SNAPP BARCODE / CROSS-FUNCTIONAL COLLABORATION','Better banners,<br>built together.','I connected performance feedback with creative decisions.')+`<div class="skill-grid"><section class="skill"><h3>Data → Content pillars</h3><p>Built content pillars with Data, using insights and software features.</p></section><section class="skill"><h3>Customer Service → Messaging</h3><p>Used Customer Service feedback to sharpen pain-point messaging.</p></section></div><h3 class="section-title">CTR analysis / Creative revisions / A/B testing</h3><div class="flow"><div><strong>01 / Performance</strong><p>Shared banner CTR data.</p></div><div><strong>02 / My role</strong><p>Reviewed results and coordinated improvements.</p></div><div><strong>03 / Design</strong><p>Refined visuals and messages for A/B tests.</p></div></div><h3 class="section-title">Review → Discuss → Revise → Test</h3><p class="lead">Ongoing sessions with Performance and Design to make banner communication clearer.</p><a class="back-link" href="#project-1">View Snapp Barcode ↗</a>`;
 if(route==='experience')return intro('CAREER','Experience.','Digital marketing across B2B SaaS, retail, fashion and travel.')+`<ol class="timeline">${[['2026','Snapp Barcode','Social Media & Content Specialist'],['2025','Trend Marketing Solutions','Social Media Marketing Specialist'],['2024–2025','Rozet Group','Digital Marketing Specialist'],['2023','Kanirush','Social Media Marketing Specialist'],['2022','Alaedin Travel Agency','Social Media Marketing Specialist'],['2021','Iriano','Social Media Marketing Specialist']].map(([date,title,role])=>`<li><span>${date}</span><div><h3>${title}</h3><p>${role}</p></div></li>`).join('')}</ol><a class="back-link" href="#work">Explore selected projects ↗</a>`;
 return null;
}
function sync(){const route=location.hash.slice(1),html=render(route);if(!html){if(dialog.open)dialog.close();return;}if(!dialog.open)lastFocus=document.activeElement;content.innerHTML=html;if(!dialog.open)dialog.showModal();dialog.scrollTop=0;document.querySelector('#close').focus();}
function closePanel(){history.replaceState(null,'',location.pathname+location.search);dialog.close();if(lastFocus?.isConnected)lastFocus.focus();}
document.querySelector('#close').addEventListener('click',closePanel);
document.querySelector('#back-home').addEventListener('click',e=>{e.preventDefault();closePanel();});
dialog.addEventListener('cancel',e=>{e.preventDefault();closePanel();});
dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closePanel();}});
window.addEventListener('hashchange',sync);
const mode=document.querySelector('#mode');
function setMode(minimal){document.body.classList.toggle('minimal',minimal);mode.setAttribute('aria-pressed',String(minimal));mode.setAttribute('aria-label',minimal?'Switch to colorful appearance':'Switch to minimal appearance');mode.querySelector('span').textContent=minimal?'Colorful':'Minimal';}
try{setMode(localStorage.getItem('portfolio-minimal')==='true');}catch{}
mode.addEventListener('click',()=>{const minimal=!document.body.classList.contains('minimal');setMode(minimal);try{localStorage.setItem('portfolio-minimal',String(minimal));}catch{}});
sync();
